name: My first workflow

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    first_job:
        name: My first job
        runs-on: ubuntu-latest
        permissions:
          contents: read
          pull-requests: write
        steps:
            - name: Greet the user
              run: |
                echo "Hello world from ${{ github.actor }}!"
                echo "Current branch is ${{ github.ref }}"
              shell: bash
            
            - name: Checkout
              uses: actions/checkout@v4.1.0

            - run: tree

            - uses: devops-actions/actionlint@v0.1.2