name: My first workflow

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    first_job:
        name: My first job
        runs-on: ubuntu-latest
        permissions:
          contents: write
          pull-requests: write
        steps:
            - run: tree

            - name: GitHub Script
              uses: actions/github-script@v7.0.1
              with:
                script: |
                  console.log(context)


            - name: Create Release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                tag: 9.10.1.2.DEV
              run: |
                gh release create "$tag" \
                  --repo="$GITHUB_REPOSITORY" \
                  --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
                  --generate-notes