name: My first workflow

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    first_job:
        name: My first job
        runs-on: ubuntu-latest
        permissions:
          contents: write
          pull-requests: write
        steps:
            - run: tree

            - uses: actions/checkout@v4

            - name: GitHub Script
              uses: actions/github-script@v7.0.1
              with:
                script: |
                  octokit.paginate("GET /repos/{owner}/{repo}/tags", {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                  }).then((issues) => {
                    issues.forEach(i => console.log(issue))
                  })

            - name: Create Release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                tag: 9.10.1.3.DEV
              run: |
                gh release create "$tag" \
                  --repo="$GITHUB_REPOSITORY" \
                  --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
                  --generate-notes